# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Tiendatek 
description: >- # this means to ignore newlines until "baseurl:"
  Tiendatek es el Sistema Punto de Venta especializado para Tiendas de Abarrotes.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-paginate

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

feed:
  path: /feed/index.xml

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: "_posts"
    values:
      layout: "post"
      permalink: /revista/:title/

form_shopkeeper_url: 'https://www.jotform.com/83334153888364'
form_shopkeeper_whatsapp_url: 'https://wa.me/525542332485?text=Hola,%20me%20gustaría%20saber%20más%20sobre%20Tiendatek%20el%20punto%20de%20venta%20para%20tiendas%20de%20abarrotes'
form_distributor_url: 'https://docs.google.com/forms/d/e/1FAIpQLSf1DHyjXjLmg_xFhAyQMqxtzlfdxahIGuiWvU1T45S1yOWDwg/viewform'
